version: "3"
services:
 mongodb:
  image: mongo:latest
  container_name: mongodb-dockercompose
  ports: 
   - 27017:27017
 msclient:
  build: .
  container_name: api-bussines-dockercompose
  ports:
   - 8082:8082
  depends_on:
   - mongodb